ANCHO_VENTANA = 1100
ALTO_VENTANA = 600
GROUND_LEVEL = 543
FPS = 60

PATH_IMAGE = "/CLASE_19_inicio_juego/images/"
DIRECTION_L = 0
DIRECTION_R = 1
GROUND_COLLIDE_H = 8 #Â Aprox Gravedad/2 + 1
DEBUG = False